[project]
name = "social-gathering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "pulp>=3.1.1",
    "streamlit>=1.45.1",
]
